// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileStructure.proto

#include "fileStructure.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace FILE_STORAGE {
class ConfigPacketDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ConfigPacket> _instance;
} _ConfigPacket_default_instance_;
}  // namespace FILE_STORAGE
static void InitDefaultsscc_info_ConfigPacket_fileStructure_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::FILE_STORAGE::_ConfigPacket_default_instance_;
    new (ptr) ::FILE_STORAGE::ConfigPacket();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::FILE_STORAGE::ConfigPacket::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ConfigPacket_fileStructure_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ConfigPacket_fileStructure_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_fileStructure_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_fileStructure_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_fileStructure_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_fileStructure_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::FILE_STORAGE::ConfigPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::FILE_STORAGE::ConfigPacket, type_),
  PROTOBUF_FIELD_OFFSET(::FILE_STORAGE::ConfigPacket, con_type_),
  PROTOBUF_FIELD_OFFSET(::FILE_STORAGE::ConfigPacket, name_),
  PROTOBUF_FIELD_OFFSET(::FILE_STORAGE::ConfigPacket, chunks_),
  PROTOBUF_FIELD_OFFSET(::FILE_STORAGE::ConfigPacket, chunk_size_),
  PROTOBUF_FIELD_OFFSET(::FILE_STORAGE::ConfigPacket, block_size_),
  PROTOBUF_FIELD_OFFSET(::FILE_STORAGE::ConfigPacket, symbol_size_),
  PROTOBUF_FIELD_OFFSET(::FILE_STORAGE::ConfigPacket, overhead_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::FILE_STORAGE::ConfigPacket)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::FILE_STORAGE::_ConfigPacket_default_instance_),
};

const char descriptor_table_protodef_fileStructure_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023fileStructure.proto\022\014FILE_STORAGE\"\316\001\n\014"
  "ConfigPacket\022$\n\004type\030\001 \001(\0162\026.FILE_STORAG"
  "E.FileType\022+\n\010con_type\030\002 \001(\0162\031.FILE_STOR"
  "AGE.ContentType\022\014\n\004name\030\003 \001(\t\022\016\n\006chunks\030"
  "\004 \001(\004\022\022\n\nchunk_size\030\005 \001(\r\022\022\n\nblock_size\030"
  "\006 \001(\004\022\023\n\013symbol_size\030\007 \001(\r\022\020\n\010overhead\030\010"
  " \001(\r*#\n\010FileType\022\010\n\004FILE\020\000\022\r\n\tDIRECTORY\020"
  "\001*#\n\013ContentType\022\n\n\006BINARY\020\000\022\010\n\004TEXT\020\001b\006"
  "proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_fileStructure_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_fileStructure_2eproto_sccs[1] = {
  &scc_info_ConfigPacket_fileStructure_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_fileStructure_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_fileStructure_2eproto = {
  false, false, descriptor_table_protodef_fileStructure_2eproto, "fileStructure.proto", 326,
  &descriptor_table_fileStructure_2eproto_once, descriptor_table_fileStructure_2eproto_sccs, descriptor_table_fileStructure_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_fileStructure_2eproto::offsets,
  file_level_metadata_fileStructure_2eproto, 1, file_level_enum_descriptors_fileStructure_2eproto, file_level_service_descriptors_fileStructure_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_fileStructure_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_fileStructure_2eproto)), true);
namespace FILE_STORAGE {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FileType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_fileStructure_2eproto);
  return file_level_enum_descriptors_fileStructure_2eproto[0];
}
bool FileType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ContentType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_fileStructure_2eproto);
  return file_level_enum_descriptors_fileStructure_2eproto[1];
}
bool ContentType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void ConfigPacket::InitAsDefaultInstance() {
}
class ConfigPacket::_Internal {
 public:
};

ConfigPacket::ConfigPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:FILE_STORAGE.ConfigPacket)
}
ConfigPacket::ConfigPacket(const ConfigPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_name(),
      GetArena());
  }
  ::memcpy(&type_, &from.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&overhead_) -
    reinterpret_cast<char*>(&type_)) + sizeof(overhead_));
  // @@protoc_insertion_point(copy_constructor:FILE_STORAGE.ConfigPacket)
}

void ConfigPacket::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ConfigPacket_fileStructure_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&overhead_) -
      reinterpret_cast<char*>(&type_)) + sizeof(overhead_));
}

ConfigPacket::~ConfigPacket() {
  // @@protoc_insertion_point(destructor:FILE_STORAGE.ConfigPacket)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ConfigPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ConfigPacket::ArenaDtor(void* object) {
  ConfigPacket* _this = reinterpret_cast< ConfigPacket* >(object);
  (void)_this;
}
void ConfigPacket::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ConfigPacket::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ConfigPacket& ConfigPacket::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ConfigPacket_fileStructure_2eproto.base);
  return *internal_default_instance();
}


void ConfigPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:FILE_STORAGE.ConfigPacket)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&overhead_) -
      reinterpret_cast<char*>(&type_)) + sizeof(overhead_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ConfigPacket::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .FILE_STORAGE.FileType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::FILE_STORAGE::FileType>(val));
        } else goto handle_unusual;
        continue;
      // .FILE_STORAGE.ContentType con_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_con_type(static_cast<::FILE_STORAGE::ContentType>(val));
        } else goto handle_unusual;
        continue;
      // string name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "FILE_STORAGE.ConfigPacket.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 chunks = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          chunks_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 chunk_size = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          chunk_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 block_size = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          block_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 symbol_size = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          symbol_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 overhead = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          overhead_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ConfigPacket::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:FILE_STORAGE.ConfigPacket)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .FILE_STORAGE.FileType type = 1;
  if (this->type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // .FILE_STORAGE.ContentType con_type = 2;
  if (this->con_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_con_type(), target);
  }

  // string name = 3;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "FILE_STORAGE.ConfigPacket.name");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_name(), target);
  }

  // uint64 chunks = 4;
  if (this->chunks() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(4, this->_internal_chunks(), target);
  }

  // uint32 chunk_size = 5;
  if (this->chunk_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->_internal_chunk_size(), target);
  }

  // uint64 block_size = 6;
  if (this->block_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(6, this->_internal_block_size(), target);
  }

  // uint32 symbol_size = 7;
  if (this->symbol_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(7, this->_internal_symbol_size(), target);
  }

  // uint32 overhead = 8;
  if (this->overhead() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(8, this->_internal_overhead(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FILE_STORAGE.ConfigPacket)
  return target;
}

size_t ConfigPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FILE_STORAGE.ConfigPacket)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 3;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // .FILE_STORAGE.FileType type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_type());
  }

  // .FILE_STORAGE.ContentType con_type = 2;
  if (this->con_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_con_type());
  }

  // uint64 chunks = 4;
  if (this->chunks() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_chunks());
  }

  // uint64 block_size = 6;
  if (this->block_size() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_block_size());
  }

  // uint32 chunk_size = 5;
  if (this->chunk_size() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_chunk_size());
  }

  // uint32 symbol_size = 7;
  if (this->symbol_size() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_symbol_size());
  }

  // uint32 overhead = 8;
  if (this->overhead() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_overhead());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConfigPacket::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:FILE_STORAGE.ConfigPacket)
  GOOGLE_DCHECK_NE(&from, this);
  const ConfigPacket* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ConfigPacket>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:FILE_STORAGE.ConfigPacket)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:FILE_STORAGE.ConfigPacket)
    MergeFrom(*source);
  }
}

void ConfigPacket::MergeFrom(const ConfigPacket& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:FILE_STORAGE.ConfigPacket)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {
    _internal_set_name(from._internal_name());
  }
  if (from.type() != 0) {
    _internal_set_type(from._internal_type());
  }
  if (from.con_type() != 0) {
    _internal_set_con_type(from._internal_con_type());
  }
  if (from.chunks() != 0) {
    _internal_set_chunks(from._internal_chunks());
  }
  if (from.block_size() != 0) {
    _internal_set_block_size(from._internal_block_size());
  }
  if (from.chunk_size() != 0) {
    _internal_set_chunk_size(from._internal_chunk_size());
  }
  if (from.symbol_size() != 0) {
    _internal_set_symbol_size(from._internal_symbol_size());
  }
  if (from.overhead() != 0) {
    _internal_set_overhead(from._internal_overhead());
  }
}

void ConfigPacket::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:FILE_STORAGE.ConfigPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConfigPacket::CopyFrom(const ConfigPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FILE_STORAGE.ConfigPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConfigPacket::IsInitialized() const {
  return true;
}

void ConfigPacket::InternalSwap(ConfigPacket* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ConfigPacket, overhead_)
      + sizeof(ConfigPacket::overhead_)
      - PROTOBUF_FIELD_OFFSET(ConfigPacket, type_)>(
          reinterpret_cast<char*>(&type_),
          reinterpret_cast<char*>(&other->type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ConfigPacket::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace FILE_STORAGE
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::FILE_STORAGE::ConfigPacket* Arena::CreateMaybeMessage< ::FILE_STORAGE::ConfigPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::FILE_STORAGE::ConfigPacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
